### ISSUE TITLE
Error while installing subtitle-fetcher

### ISSUE THREAD

**Issue by sumanthch** [ajayrfhp/subtitle-downloader#1]
showing package directory doesnot exist.

![screenshot 8](https://cloud.githubusercontent.com/assets/11132028/8075996/b1b3faea-0f64-11e5-93dd-54341897c959.png)

**Comment by ssundarraj** [comment]
Looking into it :)

**Comment by ssundarraj** [comment]
Fixed by cf74a12b0d3d45280689b0180a1fdd401e17fcd0
